### ISSUE TITLE
BUG: Camera params not working?

### ISSUE THREAD

**Issue by r01010010** [mishazawa/houdini_headless_setup#1]
I'm getting the same picture with different camera params, here are the curls:

```sh
curl --location 'http://127.0.0.1:8008/' \
--form 'hipfile="v20/demo_rock.hiplc"' \
--form 'subnet="demo_geo"' \
--form 'camera="'\''{\"position\":[-5,4,5],\"rotation\":[-30,-45,0],\"distance\":1,\"resolution\":[512,512],\"focal_length\":100, \"orbit\": 0}'\''"'

```

```sh
curl --location 'http://127.0.0.1:8008/' \
--form 'hipfile="v20/demo_rock.hiplc"' \
--form 'subnet="demo_geo"' \
--form 'camera="'\''{\"position\":[0,0,0],\"rotation\":[-30,-45,0],\"distance\":1,\"resolution\":[512,512],\"focal_length\":100, \"orbit\": 0}'\''"'
```

Both give the same exact results:

![df65992e-356c-4ef8-a723-a73f736f1986](https://github.com/mishazawa/houdini_headless_setup/assets/698953/b7025032-06f9-483d-ae7f-8407cd39ef63)

 Shouldn't they be different? We just need a frontal view for now, what would the preset be?

**Comment by mishazawa** [comment]
Yes. It looks like vectors params doesn't interpret correctly.

**Comment by mishazawa** [comment]
#2 fixed with this pr
